# Generated by Django 2.1 on 2019-11-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(null=True)),
                ('home_goals', models.IntegerField(null=True)),
                ('away_goals', models.IntegerField(null=True)),
                ('away_team_odds', models.FloatField(null=True)),
                ('home_team_odds', models.FloatField(null=True)),
                ('tie_odds', models.FloatField(null=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuteScored', models.IntegerField(null=True)),
                ('goalScorer', models.CharField(max_length=40)),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('goals', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('gamesPlayed', models.IntegerField(null=True)),
                ('yellowCards', models.IntegerField(null=True)),
                ('redCards', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=10)),
                ('injured', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('top_scorer', models.CharField(max_length=100)),
                ('Wins', models.IntegerField(null=True)),
                ('awayWins', models.IntegerField(null=True)),
                ('homeWins', models.IntegerField(null=True)),
                ('Draws', models.IntegerField(null=True)),
                ('awayDraws', models.IntegerField(null=True)),
                ('homeDraws', models.IntegerField(null=True)),
                ('Losses', models.IntegerField(null=True)),
                ('awayLosses', models.IntegerField(null=True)),
                ('homeLosses', models.IntegerField(null=True)),
                ('Points', models.IntegerField(null=True)),
                ('awayPoints', models.IntegerField(null=True)),
                ('homePoints', models.IntegerField(null=True)),
                ('GoalsFor', models.IntegerField(null=True)),
                ('awayGF', models.IntegerField(null=True)),
                ('homeGF', models.IntegerField(null=True)),
                ('GoalsAgainst', models.IntegerField(null=True)),
                ('awayGA', models.IntegerField(null=True)),
                ('homeGA', models.IntegerField(null=True)),
                ('GoalDifference', models.IntegerField(null=True)),
                ('awayGD', models.IntegerField(null=True)),
                ('homeGD', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Team'),
        ),
        migrations.AddField(
            model_name='goalevent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeamName', to='soccer.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeamName', to='soccer.Team'),
        ),
    ]
